sudo: required

language: node_js

before_install:
  - npm i -g npm@6

node_js:
  - "8"
  - "11"

before_script:
  - lerna bootstrap --hoist

script:
  - npm run lint
  - npm run tslint:once
  - npm run test